---

dci_agent: openshift            # needed for dci-agent-ctl
dci_topic: OCP-4.11

# -- Atttributes of the job --
#dci_name: "ocp-install"
#dci_configuration: "my-conf"

# Remove "debug" when your jobs are working to get them in the
# statistics:
dci_tags: ["debug"]

# -- Components --
# If you don't specify dci_components or dci_components_by_query
# you will get the latest components associated with that topic.
#
# You can specify components via the ID found from dcictl component-list
#dci_components: ['c364f2a7-2d25-4b91-9773-3448fb48d0a0']
# Or you can query by name or type and tags
#dci_components_by_query: ['name:4.11.3']
#dci_components_by_query: ['type:ocp,tags:ocp-vanilla-4.11-simple-ok']
#dci_components_by_query: ['tags:build:ga']
#If you specify both the components list will be combined.

# dci-openshift-agent settings
# defaults from /usr/share/dci-openshift-agent/group_vars/all

# By default we don't run the conformance tests
#dci_openshift_agent_conformance: openshift-conformance-minimal

# By default disconnected mode is disabled
#dci_disconnected: False

# Specify version of baremetal deploy repo, default is origin/master
#baremetal_deploy_version: origin/master

# By default we do not run cnf tests
# dci_openshift_agent_cnf_tests_mode: non-disconnected

# If you want, you can define a custom resource definition list
# dci_ocp_custom_resources:
# - name: my-custom-cr1
#   namespace: ns1
#   kind: CustomResource
#   api_version: v1
#   spec:
#     SomeSpecKey: true
#     AnotherSpecKey: "string"
# - name: my-custom-cr2
#   namespace: ns2
#   kind: CustomResource
#   api_version: v1
#   spec:
#     ExampleAuthenticationKey: "password"

...
